### ISSUE TITLE
Could not resolve an instance of Umbraco.Core.Security.BackOfficeSignInManager from the Microsoft.Owin.IOwinContext

### ISSUE THREAD

**Issue by rasmuseeg** [Shazwazza/UmbracoIdentity#24]
**Packages** 
Umbraco: 7.3.0
UmbracoIdentity: 2.0.1

**Steps:**
1. Log in to the backoffice.

**Dialog message**
Login failed for user *username*

Could not resolve an instance of Umbraco.Core.Security.BackOfficeSignInManager from the Microsoft.Owin.IOwinContext

**EXCEPTION DETAILS:**

System.NullReferenceException: Could not resolve an instance of Umbraco.Core.Security.BackOfficeSignInManager from the Microsoft.Owin.IOwinContext
**STACKTRACE:**
```
at Umbraco.Web.Editors.AuthenticationController.get_SignInManager()
   at Umbraco.Web.Editors.AuthenticationController.<PostLogin>d__f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
```

**UmbracoTrace.log**
```
 2015-10-24 22:16:18,189 [P7976/D30/T39] INFO  Umbraco.Core.UmbracoApplicationBase - Application shutdown. Details: ConfigurationChange

_shutDownMessage=CONFIG change
HostingEnvironment initiated shutdown
CONFIG change
CONFIG change
HostingEnvironment caused shutdown

_shutDownStack=   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at System.Web.Hosting.HostingEnvironment.InitiateShutdownInternal()
   at System.Web.Hosting.HostingEnvironment.InitiateShutdownWithoutDemand()
   at System.Web.HttpRuntime.ShutdownAppDomain(String stackTrace)
   at System.Web.Configuration.HttpConfigurationSystem.OnConfigurationChanged(Object sender, InternalConfigEventArgs e)
   at System.Configuration.Internal.InternalConfigRoot.OnConfigChanged(InternalConfigEventArgs e)
   at System.Configuration.BaseConfigurationRecord.OnStreamChanged(String streamname)
   at System.Web.Configuration.WebConfigurationHostFileChange.OnFileChanged(Object sender, FileChangeEvent e)
   at System.Web.DirectoryMonitor.FireNotifications()
   at System.Web.Util.WorkItem.CallCallbackWithAssert(WorkItemCallback callback)
   at System.Web.Util.WorkItem.OnQueueUserWorkItemCompletion(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
 2015-10-24 22:17:18,444 [P7976/D31/T31] INFO  Umbraco.Core.CoreBootManager - Umbraco 7.3.0 application starting on AARDA-L826
 2015-10-24 22:17:18,521 [P7976/D31/T31] INFO  Umbraco.Core.PluginManager - Determining hash of code files on disk
 2015-10-24 22:17:18,548 [P7976/D31/T31] INFO  Umbraco.Core.PluginManager - Hash determined (took 24ms)
 2015-10-24 22:17:18,828 [P7976/D31/T31] INFO  Umbraco.Core.PluginManager - Starting resolution types of umbraco.interfaces.IApplicationStartupHandler
 2015-10-24 22:17:19,565 [P7976/D31/T31] INFO  Umbraco.Core.PluginManager - Completed resolution of types of umbraco.interfaces.IApplicationStartupHandler, found 0 (took 736ms)
 2015-10-24 22:17:19,607 [P7976/D31/T31] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter
 2015-10-24 22:17:19,644 [P7976/D31/T31] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter, found 0 (took 37ms)
 2015-10-24 22:17:19,645 [P7976/D31/T31] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Core.PropertyEditors.IPropertyValueConverter
 2015-10-24 22:17:19,718 [P7976/D31/T31] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Core.PropertyEditors.IPropertyValueConverter, found 0 (took 73ms)
 2015-10-24 22:17:19,764 [P7976/D31/T31] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Web.Mvc.SurfaceController
 2015-10-24 22:17:19,875 [P7976/D31/T31] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Web.Mvc.SurfaceController, found 0 (took 109ms)
 2015-10-24 22:17:19,876 [P7976/D31/T31] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Web.WebApi.UmbracoApiController
 2015-10-24 22:17:19,944 [P7976/D31/T31] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Web.WebApi.UmbracoApiController, found 0 (took 68ms)
 2015-10-24 22:17:20,036 [P7976/D31/T31] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Core.Media.IThumbnailProvider
 2015-10-24 22:17:20,091 [P7976/D31/T31] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Core.Media.IThumbnailProvider, found 0 (took 54ms)
 2015-10-24 22:17:20,092 [P7976/D31/T31] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Core.Media.IImageUrlProvider
 2015-10-24 22:17:20,148 [P7976/D31/T31] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Core.Media.IImageUrlProvider, found 0 (took 56ms)
 2015-10-24 22:17:21,871 [P7976/D31/T31] INFO  Umbraco.Core.DatabaseContext - CanConnect = True
 2015-10-24 22:17:22,611 [P7976/D31/T31] INFO  Umbraco.Core.DatabaseContext - CanConnect = True
 2015-10-24 22:17:22,616 [P7976/D31/T31] INFO  Umbraco.Core.DatabaseContext - CanConnect = True
 2015-10-24 22:17:22,781 [P7976/D31/T31] WARN  Umbraco.Core.Sync.DatabaseServerMessenger - No last synced Id found, this generally means this is a new server/install. The server will rebuild its caches and indexes and then adjust it's last synced id to the latest found in the database and will start maintaining cache updates based on that id
 2015-10-24 22:17:22,975 [P7976/D31/T31] INFO  umbraco.content - Load Xml from file...
 2015-10-24 22:17:22,989 [P7976/D31/T31] INFO  umbraco.content - Loaded Xml from file.
 2015-10-24 22:17:23,016 [P7976/D31/T31] INFO  umbraco.content - Loading content from database...
 2015-10-24 22:17:27,065 [P7976/D31/T31] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Core.PropertyEditors.IParameterEditor
 2015-10-24 22:17:27,153 [P7976/D31/T31] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Core.PropertyEditors.IParameterEditor, found 0 (took 87ms)
 2015-10-24 22:17:29,560 [P7976/D31/T74] INFO  umbraco.content - Save Xml to file...
 2015-10-24 22:17:29,613 [P7976/D31/T40] INFO  umbraco.content - Saved Xml to file.
 2015-10-24 22:17:30,362 [P7976/D31/T46] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Core.Persistence.Mappers.BaseMapper
 2015-10-24 22:17:30,402 [P7976/D31/T46] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Core.Persistence.Mappers.BaseMapper, found 0 (took 40ms)
 2015-10-24 22:17:31,365 [P7976/D31/T46] ERROR Archetype.PropertyEditors.ArchetypePropertyEditor+ArchetypePropertyValueEditor - Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Archetype.PropertyEditors.ArchetypePropertyEditor.ArchetypePropertyValueEditor.ConvertDbToString(Property property, PropertyType propertyType, IDataTypeService dataTypeService)
 2015-10-24 22:17:31,368 [P7976/D31/T46] ERROR Archetype.PropertyEditors.ArchetypePropertyEditor+ArchetypePropertyValueEditor - Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Archetype.PropertyEditors.ArchetypePropertyEditor.ArchetypePropertyValueEditor.ConvertDbToString(Property property, PropertyType propertyType, IDataTypeService dataTypeService)
 2015-10-24 22:17:31,525 [P7976/D31/T46] ERROR Archetype.PropertyEditors.ArchetypePropertyEditor+ArchetypePropertyValueEditor - Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Archetype.PropertyEditors.ArchetypePropertyEditor.ArchetypePropertyValueEditor.ConvertDbToString(Property property, PropertyType propertyType, IDataTypeService dataTypeService)
 2015-10-24 22:17:31,738 [P7976/D31/T31] INFO  Umbraco.Web.Cache.CacheRefresherEventHandler - Initializing Umbraco internal event handlers for cache refreshing
 2015-10-24 22:17:31,801 [P7976/D31/T31] INFO  Umbraco.Web.Search.ExamineEvents - Initializing Examine and binding to business logic events
 2015-10-24 22:17:31,804 [P7976/D31/T31] INFO  Umbraco.Web.Search.ExamineEvents - Adding examine event handlers for index providers: 3
 2015-10-24 22:17:31,874 [P7976/D31/T31] INFO  Umbraco.Core.CoreBootManager - Umbraco application startup complete (took 13581ms)
 2015-10-24 22:17:34,071 [P7976/D31/T40] INFO  Umbraco.Core.Sync.ApplicationUrlHelper - ApplicationUrl: http://localhost:54964/umbraco (UmbracoModule request)
 2015-10-24 22:18:36,913 [P7976/D31/T10] INFO  umbraco.BusinessLogic.Log - Log scrubbed.  Removed all items older than 2015-10-23 22:18:36
```

**Comment by Shazwazza** [comment]
When posting issues you need to give some details, steps to reproduce, etc.. A stack trace isnt exactly a great big report. Can you please provide steps to reproduce your issue?

**Comment by rasmuseeg** [comment]
Well i just logged in to the Umbraco Backoffice

**Comment by rasmuseeg** [comment]
Does the UmbracoLog.log details say anything to you?

**Comment by Shazwazza** [comment]
Ok, that's a start. What else? What versions are you using, etc... How was I supposed to know that you got this error from logging into the back office. The more details you provide, the easier things are to fix, the less back and forth like this is required. Thing about how you'd like to receive a big report.

**Comment by rasmuseeg** [comment]
Sorry, i didn't mean to offend you by any means! You have my deepest respect.

I'm so sorry for reporting it, before having collected all the logs/traces.

**Comment by Shazwazza** [comment]
Sorry didn't mean to sound upset, just get too many bug reports that have unclear details. I'll have a look on Monday, what umb version is this for? 7.3?

**Comment by rasmuseeg** [comment]
Yes, updated the details above.

**Comment by rasmuseeg** [comment]
PM > Update-Package -reinstall UmbracoIdentity
Fixes the issue, not sure where i went wrong. Properly a Web.config issue.
