### ISSUE TITLE
Umbraco.MemberHasAccess throws error when previewing from backoffice

### ISSUE THREAD

**Issue by rasmuseeg** [Shazwazza/UmbracoIdentity#42]
package.config
```
  <package id="UmbracoCms" version="7.3.7" targetFramework="net452" />
  <package id="UmbracoCms.Core" version="7.3.7" targetFramework="net452" />
  <package id="UmbracoCms.IdentityExtensions" version="1.0.0" targetFramework="net452" />
  <package id="UmbracoIdentity" version="3.0.2" targetFramework="net452" />
```

The following razor view, throws error when previewing from backoffice.
```
@inherits UmbracoTemplatePage
@using System.Web.Mvc.Html;
@using Fodterapeut.Web.Controllers;
@using Umbraco.Web;
@using Umbraco.Web.Models;
@using Umbraco.Core.Logging;
@{
    var loginStatusModel = Members.GetCurrentLoginStatus();

    Html.EnableClientValidation();
    Html.EnableUnobtrusiveJavaScript();

    var site = Model.Content.AncestorOrSelf(1);
    var protectedNodes = Enumerable.Empty<UmbracoLinksPicker.Models.Link>();
    if (Members.IsLoggedIn())
    {
        var links = Model.Content.GetPropertyValue("memberDropdownMenu", true, Enumerable.Empty<UmbracoLinksPicker.Models.Link>());
        try
        {
            protectedNodes = (
                from link in links
                where link.Content == null
                || (link.Content.IsVisible()
                    && Umbraco.IsProtected(link.Content.Path)
                    && Umbraco.MemberHasAccess(link.Content.Path))
                select link
            ).ToList();

        } catch (Exception ex)
        {
            LogHelper.Error(this.GetType(), "Failed to render member menu for: " + User.Identity.Name, ex);
        }
    }

    var logoutModel = new PostRedirectModel();

    var forgotPasswordPage = Model.Content.Ancestor(1).Descendant("AccountResetPassword");

    if (Members.IsLoggedIn())
    {
        <li>
            <a href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">@loginStatusModel.Name<span class="caret"></span></a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
                @foreach (var node in protectedNodes)
                {
                    <li><a href="@node.Url" target="@node.Target">@node.Name</a></li>
                }
                <li role="separator" class="divider"></li>
                @if (forgotPasswordPage != null)
                {
                    <li><a href="@forgotPasswordPage.Url">Skift adgangskode</a></li>
                }
                <li><a href="javascript:document.getElementById('logoutForm').submit();">Log ud</a></li>
            </ul>
        </li>

        using (Html.BeginUmbracoForm<AccountController>("HandleLogout", null, new { @id = "logoutForm" }))
        {
            @Html.HiddenFor(m => logoutModel.RedirectUrl)
        }
    } else
    {
        <li><a href="@Model.Content.AncestorOrSelf(1).Descendant("Account").Url">Log ind</a></li>
    }
}
```

This is from umbracoLog:
```
2016-03-09 10:52:28,148 [P4964/D2/T38] ERROR ASP._Page_views_Account__LoginStatus_cshtml - Failed to render member menu for: isupport@datagraf.dk
System.NullReferenceException: Object reference not set to an instance of an object.
   at Umbraco.Core.Services.PublicAccessServiceExtensions.HasAccess(IPublicAccessService publicAccessService, String path, MembershipUser member, RoleProvider roleProvider)
   at ASP._Page_views_Account__LoginStatus_cshtml.<Execute>b__0(Link link) in c:\inetpub\wwwroot\www.fodterapeut.dk\Views\Account\_LoginStatus.cshtml:line 23
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ASP._Page_views_Account__LoginStatus_cshtml.Execute() in c:\inetpub\wwwroot\www.fodterapeut.dk\Views\Account\_LoginStatus.cshtml:line 21
 2016-03-09 10:52:29,269 [P4964/D2/T38] ERROR Umbraco.Core.UmbracoApplicationBase - An unhandled exception occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Umbraco.Core.Services.PublicAccessServiceExtensions.HasAccess(IPublicAccessService publicAccessService, String path, MembershipUser member, RoleProvider roleProvider)
   at ASP._Page_Views_Partials_Dropdowns__Links_cshtml.DisplayLock(IPublishedContent content) in c:\inetpub\wwwroot\www.fodterapeut.dk\Views\Partials\Dropdowns\_Links.cshtml:line 45
   at ASP._Page_Views_Partials_Dropdowns__Links_cshtml.Execute() in c:\inetpub\wwwroot\www.fodterapeut.dk\Views\Partials\Dropdowns\_Links.cshtml:line 28
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at Umbraco.Core.Profiling.ProfilingView.Render(ViewContext viewContext, TextWriter writer)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData)
   at ASP._Page_Views_Shared__Navbar_cshtml.<>c__DisplayClass3.<MenuItem>b__1(TextWriter __razor_helper_writer) in c:\inetpub\wwwroot\www.fodterapeut.dk\Views\Shared\_Navbar.cshtml:line 98
   at ASP._Page_Views_Shared__Navbar_cshtml.<>c__DisplayClass8.<RenderItems>b__7(TextWriter __razor_helper_writer) in c:\inetpub\wwwroot\www.fodterapeut.dk\Views\Shared\_Navbar.cshtml:line 108
   at ASP._Page_Views_Shared__Navbar_cshtml.Execute() in c:\inetpub\wwwroot\www.fodterapeut.dk\Views\Shared\_Navbar.cshtml:line 52
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at Umbraco.Core.Profiling.ProfilingView.Render(ViewContext viewContext, TextWriter writer)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData)
   at ASP._Page_Views_Layout_cshtml.Execute() in c:\inetpub\wwwroot\www.fodterapeut.dk\Views\Layout.cshtml:line 40
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.WebPages.WebPageBase.RenderSurrounding(String partialViewName, Action`1 body)
   at System.Web.WebPages.WebPageBase.PopContext()
   at Umbraco.Core.Profiling.ProfilingView.Render(ViewContext viewContext, TextWriter writer)
   at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

UmbracoIdentityStartup.cs
```
public class UmbracoIdentityStartup : UmbracoDefaultOwinStartup {
 
        public override void Configuration(IAppBuilder app)
        {
            base.Configuration(app);

            //Single method to configure the Identity user manager for use with Umbraco
            app.ConfigureUserManagerForUmbracoMembers<UmbracoApplicationMember>();

            // Enable the application to use a cookie to store information for the 
            // signed in user and to use a cookie to temporarily store information 
            // about a user logging in with a third party login provider 
            // Configure the sign in cookie
            app.UseCookieAuthentication(
                //You can modify these options for any customizations you'd like
                new FrontEndCookieAuthenticationOptions());

            app.UseExternalSignInCookie(DefaultAuthenticationTypes.ExternalCookie);
       }
}
```
Any help to overcome this problem?

**Comment by rasmuseeg** [comment]
I'm not what the title should be.

**Comment by rasmuseeg** [comment]
After some digging i found that the following return null GetCurrentMember()

**Comment by rasmuseeg** [comment]
Updated to Umbraco 7.4.2 and Umbracidentity.Core nuget package
