### ISSUE TITLE
UmbracoIdentity.sdf file sharing violation

### ISSUE THREAD

**Issue by avaco** [Shazwazza/UmbracoIdentity#63]
So I am getting the following error in the logs, eveytime I try to access something in the backend, without any other users connecting to the site.  No matter how much time I wait and try again it keeps giving me that error, any ideas? 

 2017-01-09 16:47:44,672 [P3328/D24/T28] ERROR Umbraco.Core.UmbracoApplicationBase - An unhandled exception occurred
System.Data.SqlServerCe.SqlCeException (0x80004005): There is a file sharing violation. A different process might be using the file. [ D:\home\site\wwwroot\App_Data\UmbracoIdentity.sdf ]
   at System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   at System.Data.SqlServerCe.SqlCeConnection.Open()
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.<>c__DisplayClass1.<ExecuteAction>b__0()
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction(Action action)
   at Umbraco.Core.Persistence.PetaPocoConnectionExtensions.OpenWithRetry(IDbConnection connection, RetryPolicy retryPolicy)
   at Umbraco.Core.Persistence.PetaPocoConnectionExtensions.OpenWithRetry(IDbConnection connection)
   at Umbraco.Core.Persistence.Database.OpenSharedConnection()
   at Umbraco.Core.Persistence.Database.ExecuteScalar[T](String sql, Object[] args)
   at Umbraco.Core.Persistence.SqlSyntax.SqlCeSyntaxProvider.DoesTableExist(Database db, String tableName)
   at UmbracoIdentity.ExternalLoginStore..ctor() in X:\Projects\Umbraco\UmbracoIdentity\src\UmbracoIdentity\ExternalLoginStore.cs:line 43
   at UmbracoIdentity.UmbracoMembersUserManager`1.Create(IdentityFactoryOptions`1 options, IMemberService memberService, IMemberTypeService memberTypeService, IMemberGroupService memberGroupService, IExternalLoginStore externalLoginStore, IdentityEnabledMembersMembershipProvider membershipProvider) in X:\Projects\Umbraco\UmbracoIdentity\src\UmbracoIdentity\UmbracoMembersUserManager.cs:line 81
   at UmbracoIdentity.AppBuilderExtensions.<>c__DisplayClass0_0`1.<ConfigureUserManagerForUmbracoMembers>b__0(IdentityFactoryOptions`1 o, IOwinContext c) in X:\Projects\Umbraco\UmbracoIdentity\src\UmbracoIdentity\AppBuilderExtensions.cs:line 36
   at Microsoft.AspNet.Identity.Owin.IdentityFactoryProvider`1.Create(IdentityFactoryOptions`1 options, IOwinContext context)
   at Microsoft.AspNet.Identity.Owin.IdentityFactoryMiddleware`2.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Identity.Owin.IdentityFactoryMiddleware`2.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Identity.Owin.IdentityFactoryMiddleware`2.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContextStage.<RunApp>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.<DoFinalWork>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar)
   at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.EndFinalWork(IAsyncResult ar)
   at System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by Shazwazza** [comment]
* What version are you using?
* Are you load balancing?
* Anything else I'd need to know?

**Comment by avaco** [comment]
Hi

I am using Umbraco 7.5.4 and Identity 4.0 

I might be load balancing, I am using azure websites on the Stardard 2 plan, but there are no users, just a couple of us testing, this happens with the ARR token and without it (used so that you always connect to the same server in that session)

The Umbrabo.sdf is not giving that error, I would assume that is used more that the Identity, and I find it weird that it opens it up in the backend, since its used for the frontend.  

We are using Azure AD to authenticate the users, without any issues as far as we can tell. 

This does not happen on the local machine, neither on other test site that we have on azure on the basic plan.  We do not have any plugins, and although our articles have a read, like and share, count, we save those in firebase, so that we don't do several writes to the Umbraco DB.

Also we are getting this error, when we open the log its the sharing violation error that I posted first. This keeps comming up every 4 or 5 interactions in the backend, sometimes more often.
![image](https://cloud.githubusercontent.com/assets/4973875/21818529/d1587302-d72d-11e6-8129-71fb34979b29.png)

**Comment by Shazwazza** [comment]
We used to have a doc on the Wiki stating that this project would not support Load Balancing - since it cannot when using a SQL CE database file. The latest version does and it stores the information in the same database as Umbraco, you will need to upgrade to the latest version which also requires the latest Umbraco version, see release/upgrade notes: https://github.com/Shazwazza/UmbracoIdentity/releases/tag/v5.0.0
